Algoritmo "meusalario"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/03/2023
Var
// Seção de Declarações das variáveis 
   nome: caractere
   sal: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Qual o nome do(a) funcionário(a)? ")
   Leia(nome)
   Escreva("Qual foi o salário do(a) funcionário(a)? ")
   Leia(sal)
   Escreval("Nome do(a) funcionário(a): ", nome)
   Escreval("Salário: R$ ", sal:1:2)
   Escreval("O(a) funcionário(a) ", nome, " teve um salário de R$", sal:1:2, " em junho")

Fimalgoritmo