Algoritmo "combinacoes"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/03/2023
Var
// Seção de Declarações das variáveis 
   C1, C2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Para C1 :=1 ate 3 faca
        Para C2 :=1 ate 3 faca
           Escreval (C1, C2)
        FimPara
   FimPara

Fimalgoritmo