Algoritmo "minha-idade"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/03/2023
Var
// Seção de Declarações das variáveis 
   anoAtual, anoNasc, idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva ("Em que ano nós estamos? ")
   Leia (anoAtual)
   Escreva ("Em que ano eu nasci? ")
   Leia (anoNasc)
   idade <- anoAtual - anoNasc
   Escreva ("Então eu tenho,", idade, " anos")
   

Fimalgoritmo