Algoritmo "SOMA-REFERENCIA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/03/2023
Var
// Seção de Declarações das variáveis 
   X, Y: Inteiro
   Procedimento soma(A, B: inteiro)
   Inicio
         A <- A + 1
         B <- B + 2
         Escreval ("Valor de A:", A)
         Escreval ("Valor de B:", B)
         Escreval ("A soma vale", A+B)
   FimProcedimento

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   x <- 4
   y <- 8
   soma(X, Y)
   Escreval ("Valor de X:", X)
   Escreval ("Valor de Y:", Y)

Fimalgoritmo