Algoritmo "escopo-procedimento"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/03/2023
Var
// Seção de Declarações das variáveis 
   n1, n2: inteiro
   Procedimento Rotina(A, B: Inteiro)
   Var
      X, Y: INTEIRO
   Inicio
         X <- A
         Y <- B
         Escreva (n1, n2, A, B, X, Y)
   FimProcedimento

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   n1 <- 5
   n2 <- 3
   Rotina(n1, n2)
   Escreva(n1, n2, A, B, X, Y)

Fimalgoritmo